### ISSUE TITLE
Tracking issue for processor overhaul

### ISSUE THREAD

**Issue by rphmeier** [rphmeier/rust_toy_engine#44]
Here's my plan:

- [ ] Simplify `WorldHandle` so it doesn't give access to state at all, but does give access to the thread pool
- [ ] Implement new locking mechanism, probably with a lot of manipulation of the `Components` trait
- [ ] Add an API over `WorldHandle` for using different locking granularities, etc.
- [ ] Simplify `Processor` to have only a `process` member function.
- [ ] Add processor "prefabs" like `ForEachProcessor`, which will take the place of the current `Processor`
